#!/usr/bin/env bash
set -eou pipefail

# If using Linux/Debian, use -i w/o -i '' notation; if OS X, use -i ''
sed -i 's/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/'$(date +%Y-%m-%d)'/g'     README.md
sed -ri 's/(Incremented: )([0-9]+)/echo "Incremented: $((\2+1))"/ge'  README.md

git commit -am "'$(date +%Y-%m-%d)'"
